   ASSIGNMENT 3

1.Write a function to compute 5/0 and use try/except to catch the exceptions.

In [6]:
try:
    result = 5/0
    raise
except ZeroDivisionError:
    print("Invalid Division error")
    
       

Invalid Division error



2.Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

Output should come as below:

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.

In [7]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

list1 = [[x,y,z] for x in subjects for y in verbs for z in objects]
for element in list1:
    print(*element, sep = " ")

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


TASK 2
Question 1:
Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.


In [14]:
import numpy as np
def compute_vandermonde(array,power,incr):
    return np.vander(array,power,incr)
arr = [1,2,3,4]    
print(compute_vandermonde(arr,4,False))

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
